import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { useState } from 'react';
import axios from "axios"


const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  const [code, setCode] = useState("");

  const handleSubmit = async()=>{
    const payload = {
      language: "cpp",
      code
    };
    const output = await axios.post("http://localhost:5000/run", payload);
    console.log(output);
  }
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='flex flex-col justify-center items-center'>
        <h1 className="text-3xl font-bold underline">Write your code here mr. Om Prakash</h1>
        <textarea name="codeBox" value={code} onChange={(e)=>setCode(e.target.value)} cols="60" rows="10" className='border-4'></textarea>
        <button className='border-2 bg-blue-300 p-4 rounded-lg' onClick={handleSubmit}>Submit</button>
      </main>
    </>
  );
}
